/**
 * @fileoverview gRPC-Web generated client stub for QuestSearch
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: QuestSearch.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.QuestSearch = require('./QuestSearch_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.QuestSearch.QuestSearchServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.QuestSearch.QuestSearchServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.QuestSearch.QuestionRequest,
 *   !proto.QuestSearch.QuestionResponse>}
 */
const methodDescriptor_QuestSearchService_GetQuestions = new grpc.web.MethodDescriptor(
  '/QuestSearch.QuestSearchService/GetQuestions',
  grpc.web.MethodType.UNARY,
  proto.QuestSearch.QuestionRequest,
  proto.QuestSearch.QuestionResponse,
  /**
   * @param {!proto.QuestSearch.QuestionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.QuestSearch.QuestionResponse.deserializeBinary
);


/**
 * @param {!proto.QuestSearch.QuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.QuestSearch.QuestionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.QuestSearch.QuestionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.QuestSearch.QuestSearchServiceClient.prototype.getQuestions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/QuestSearch.QuestSearchService/GetQuestions',
      request,
      metadata || {},
      methodDescriptor_QuestSearchService_GetQuestions,
      callback);
};


/**
 * @param {!proto.QuestSearch.QuestionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.QuestSearch.QuestionResponse>}
 *     Promise that resolves to the response
 */
proto.QuestSearch.QuestSearchServicePromiseClient.prototype.getQuestions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/QuestSearch.QuestSearchService/GetQuestions',
      request,
      metadata || {},
      methodDescriptor_QuestSearchService_GetQuestions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.QuestSearch.Empty,
 *   !proto.QuestSearch.GetUniqueTypesResponse>}
 */
const methodDescriptor_QuestSearchService_GetUniqueTypes = new grpc.web.MethodDescriptor(
  '/QuestSearch.QuestSearchService/GetUniqueTypes',
  grpc.web.MethodType.UNARY,
  proto.QuestSearch.Empty,
  proto.QuestSearch.GetUniqueTypesResponse,
  /**
   * @param {!proto.QuestSearch.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.QuestSearch.GetUniqueTypesResponse.deserializeBinary
);


/**
 * @param {!proto.QuestSearch.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.QuestSearch.GetUniqueTypesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.QuestSearch.GetUniqueTypesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.QuestSearch.QuestSearchServiceClient.prototype.getUniqueTypes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/QuestSearch.QuestSearchService/GetUniqueTypes',
      request,
      metadata || {},
      methodDescriptor_QuestSearchService_GetUniqueTypes,
      callback);
};


/**
 * @param {!proto.QuestSearch.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.QuestSearch.GetUniqueTypesResponse>}
 *     Promise that resolves to the response
 */
proto.QuestSearch.QuestSearchServicePromiseClient.prototype.getUniqueTypes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/QuestSearch.QuestSearchService/GetUniqueTypes',
      request,
      metadata || {},
      methodDescriptor_QuestSearchService_GetUniqueTypes);
};


module.exports = proto.QuestSearch;

